# -*- coding: utf-8 -*-
"""demo1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bye5cg_yz90ovikhgSrP45ZCXY8pQ_4b
"""

import numpy as np

x = np.array([1,2,3])
print(x)

x = np.arange(10)
print(x)
x = np.arange(2,7)
print(x)
x = np.arange(-5,5,2)
print(x)

y = np.arange(0,5.1,0.5)
print(y)

y = np.arange(2,22,2)
print(y)

z = np.arange(-30,31,10)
print(np.abs(z))

y1 = y[2:5] #index
y2 = y[-1]
print(y1)
print(y2)

import matplotlib.pyplot as plt
f = 3
t = np.linspace(0,2,100)
x = np.sin(2*np.pi*f*t)

plt.plot(t,x)
plt.grid()
plt.xlabel('Time', fontsize = 16)
plt.ylabel('Intensity', fontsize = 16)

y = x**2
plt.plot(t,x)
plt.plot(t,y)
plt.grid()

import pandas as pd
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data')
df.head(6)

names = ['mpg', 'cylinders','displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin', 'car name']
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data', header=None,delim_whitespace=True,names=names,na_values='?')
df.head(6)

df.shape

df.columns.to_list()

x = np.array(df['weight'])
y = np.array(df['mpg'])
plt.plot(x,y,'o')
plt.grid()
plt.xlabel('weight')
plt.ylabel('mpg')

mx = np.mean(x)
my = np.mean(y)
print(mx)
print(my)

z = np.array(df['horsepower'])
np.mean(z)

df1 = df[['mpg', 'horsepower']]
df2 = df.dropna()
x = np.array(df2['mpg'])
y = np.array(df2['horsepower'])
plt.plot(x,y,'o')
plt.xlabel('mpg')
plt.ylabel('horsepower')
plt.grid()